### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by ChaplyginWezom** [johannebert/laravel-spam-protector#10]
Hi! Will be new version released any time soon? I really need stable version, that allows PHP 8 to use in my project.
Thanks in advance!

**Comment by p-andrey** [comment]
@johannebert Hello. You can make a release with support for PHP 8?

**Comment by johannebert** [comment]
Hey, i added support for PHP 8 and released it v6. 
But at the moment i don't have enough time to test it. So if you run into issues please submit a PR.
Thank you.
